apiVersion: v1
kind: Pod
metadata:
  name: worker-app-Pod2
  labels:
    name: worker-app-Pod
    app: demo-voting-app
spec:
  containers:
  - name: worker-app
    image: dockersamples/examplevotingapp_worker
